name: Build on DockerHub

on:
  push:
    branches:
      - main # Defina o branch que aciona o workflow, caso queira
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          # dockerfile: ./Dockerfile   # Se o Dockerfile estiver em um local diferente, descomente e defina o caminho correto
          tags: kseraos/webacademy:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo deploy
        run: echo "Deploy com sucesso!"
